title: Oliver Gilliland - Product Manager
email: omgilliland@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Awesome site description goes here. It will appear in document head meta (for
  Google search results) and in feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ollymg
github_username:  ogilliland

# Build settings
markdown:      kramdown
highlighter:   rouge
permalink:     /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-archives

collections:
  projects:
    output: true
    permalink: /work/:name/

jekyll-archives:
  enabled:
    - year
    - month
  layout:  blog
  permalinks:
    year: /blog/:year/
    month: /blog/:year/:month/
    day: /blog/:year/:month/:day/
    tag: /search/tag/:name/
    category: /search/category/:name/