title: Oliver Gilliland - Product Manager
email: omgilliland@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Awesome site description goes here. It will appear in document head meta (for
  Google search results) and in feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ogilliland.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ollymg
github_username: ogilliland

twitter:
  username: ollymg
  card: summary

social:
  name: Oliver Gilliland
  links:
    - https://www.linkedin.com/in/oliver-gilliland/
    - https://github.com/ogilliland
    - https://twitter.com/ollymg

google_site_verification: 42tKFqrTn6wwvk4QxzMplSps47pxtLB1GFX_Dm2Upu0

# build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title/

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /work/:name/

jekyll-archives:
  enabled:
    - year
    - month
    - tag
    - category
  layouts:
    year: archive
    month: archive
    tag: archive
    category: archive
  permalinks:
    year: /blog/:year/
    month: /blog/:year/:month/
    tag: /search/tag/:name/
    category: /search/category/:name/